# Generated by Django 6.0.2 on 2026-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lien',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL'),
        ),
    ]
